server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:3306/postgres
        username: postgres
        password: 1234
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true

jwt:
    secret: ABCD1234EFGH5678IJKL9012MNOP3456QRST7890UVWX1234YZ==
    access-time: 900000
    refresh-time: 604800000